# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e18a577aae3a90e8e59bb8cf9215830455f045b35ae33d8879a91edfe77aca3019810cb49c219928975e42771f92f6429c4983e4faf27d1896847773f3a276d2

test:
  secret_key_base: 8e0f1ec9f812fa693e4e32f4ef1d0c186d59409200402939c79ccea5239973bd85dea627fa43a5e73a30bda074fd9254d1c80e31618c70ec06c8a6ff285e04c4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
