# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6e31534a9c4f27735f3fcca0748f92ad3e74e0c74eeb08e76ffd2ac917a1ba77cb27a664b9fb45c852b832a41c6d9dc6b3a4bfc19479a91758c26fedc9661108

test:
  secret_key_base: 617be0bfef1ae523d23b92d2b84577e21ae0de4dcfbb6d337e7a2916baf766dc294c5c2e1954c3d822df8aa36c8bded14f573f636b7d8ae7b3a80ae00fdeaa41

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
